# Generated by Django 4.0.5 on 2022-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='languages',
            field=models.ManyToManyField(to='instructors.language'),
        ),
    ]
